[package]
name = "blue_noise"
version = "0.1.0"
edition = "2021"

[dependencies]
plotly = "0.10"
rand = "0.8.5"   # For random color generation
honeycomb = { git = "https://github.com/LIHPC-Computational-Geometry/honeycomb", rev = "99f3b5d", features = ['render']}
wgpu = "23"
pollster = "0.3"
log = "0.4"
bytemuck = "1.19"
flume = "0.11"
env_logger = "0.11"
clap = { version = "4.5.21", features = ["derive"] }
image = "0.24.7"  # For image generation
once_cell = "1.19.0"  # For lazy static initialization

# benches
[dev-dependencies]
iai-callgrind = "0.14.0"
criterion = "0.5.1"

[profile.release]
debug = true

[profile.bench]
debug = true

[[bench]]
name = "generate_cells"
harness = false

[[bench]]
name = "binary_benchmark"
harness = false

[[bench]]
name = "generate_mesh"
harness = false

[[bench]]
name = "generate_points"
harness = false

